FROM coopersoft/canal-osbase:aarch64-v2

MAINTAINER agapple (jianghang115@gmail.com)


#ENV DOWNLOAD_LINK="https://github.com/alibaba/canal/releases/download/canal-1.1.6/canal.deployer-1.1.6.tar.gz"

# install canal
COPY image/ /tmp/docker/

RUN mkdir -p /home/admin/canal-server

COPY ./canal.deployer-1.1.6/ /home/admin/canal-server/

RUN \
    cp -R /tmp/docker/alidata /alidata && \
    chmod +x /alidata/bin/* && \
    mkdir -p /home/admin && \
    cp -R /tmp/docker/app.sh /home/admin/  && \
    cp -R /tmp/docker/admin/* /home/admin/  && \
    /bin/cp -f alidata/bin/lark-wait /usr/bin/lark-wait && \
    tar zxvf /tmp/node_exporter.tar.gz -C /home/admin && \
    ln -s /home/admin/node_exporter-0.18.1.linux-arm64 /home/admin/node_exporter && \
    mkdir -p home/admin/canal-server/logs  && \
    chmod +x /home/admin/*.sh  && \
    chmod +x /home/admin/bin/*.sh  && \
    chown admin: -R /home/admin && \
    yum clean all && \
    true

# 11110 admin , 11111 canal , 11112 metrics, 9100 exporter
EXPOSE 11110 11111 11112 9100

WORKDIR /home/admin

ENTRYPOINT [ "/alidata/bin/main.sh" ]
CMD [ "/home/admin/app.sh" ]